name: UbuntuX86BuildTest

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo ./install_dep.sh
      - name: Build
        run: |
          ./build_cmake.sh
